version: "3.9"

networks:
  petclinic-net:

volumes:
  petclinic-db-data:
  petclinic-logs:

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - petclinic-db-data:/var/lib/mysql
    networks:
      - petclinic-net

  petclinic:
    image: petclinic-layers2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "3030:8080"
    depends_on:
      - db
    volumes:
      - petclinic-logs:/app/logs
    networks:
      - petclinic-net
